
project_id = "lswyxckumfvkruxsqvau"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "dual"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 1025
pop3_port = 1110

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true
bucket_limit = 100
upload_limit = "1GiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_autoconfirm = false
enable_phone_confirmations = false
enable_phone_autoconfirm = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1m"
secure_password_change = false

[auth.email.smtp]
enable_signup = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.figma]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""

[auth.external.fly]
enabled = false
client_id = ""
secret = ""

[functions.jotform-webhook]
verify_jwt = false
