// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lswyxckumfvkruxsqvau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzd3l4Y2t1bWZ2a3J1eHNxdmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjA3ODksImV4cCI6MjA2NTM5Njc4OX0.QaZdrKqZ3D92nWulx37kRJM3XPhEnktLz2JmKT9c3P8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);